################################# training settings  #################################
# data
dataset_name: 'radar'
train_data_root: /mnt/radar/2hour/2019
test_data_root: /mnt/radar/2hour/valid
# result
exp_name: ConvLSTM
result_root: /mnt/result/ny/

input_length: 5
total_length: 25
img_width: 360
img_height: 360
padding_H: 0
padding_W: 0
img_channel: 1
num_workers: 4


# model
model_name: convlstm
pretrained_model: ~
strict: False
num_hidden: [16,32,64,64]
filter_size: 5
stride: 1
patch_size: 1
layer_norm: 1

# scheduled sampling
scheduled_sampling: 1
sampling_stop_iter: 10000
sampling_start_value: 1.0
sampling_changing_rate: 0.0001

# optimization
lr: 0.0001
max_iterations: 60000
# lr_steps: [5000, 10000, 15000, 20000, 25000]
lr_steps: ~
reverse_input: 0
batch_size: 4
test_batch_size: 8
epochs: 100
display_interval: 5
test_interval: 500
snapshot_interval: 5000
num_save_samples: 10
gpu_ids: [0]