################################# training settings  #################################
# data
dataset_name: 'satellite'
data_root: /mnt/A/satelite/datasets/
save_dir: checkpoints/PhyDNet
gen_frm_dir: results/PhyDNet
tb_log_dir: tb_log/PhyDNet/
save_root: results/PhyDNet/
input_length: 4
total_length: 12
img_width: 400
img_height: 300
img_channel: 1
num_workers: 4


# model
model_name: PhyDNet
pretrained_model: /home/ices/yl/SatelliteSP/checkpoints/PhyDNet_oneframe/model-12800-0.00048332618398126215.ckpt
strict: True

# gru:
num_hidden: [128,128,64]
filter_size: 3
stride: 1
patch_size: 1 # not support reshape patch
layer_norm: 1

# phy:
phy_num_hidden: [49]
phy_filter_size: 7

# encoder:
encode_input: True
encoder:
  name: dcgan
  skip_connect: True
  context_channel: 64
# input shape: [300//4, 400//4]

# scheduled sampling
scheduled_sampling: 1
sampling_stop_iter: 10000
sampling_start_value: 1.0
sampling_changing_rate: 0.0001

# optimization
lr: 0.0001
max_iterations: 30000
lr_steps: [5000, 10000, 15000, 20000, 25000]
reverse_input: 1
test_batch_size: 5
batch_size: 6
epochs: 100
display_interval: 50
test_interval: 800
snapshot_interval: 5000
num_save_samples: 10
gpu_ids: [0]