################################# training settings  #################################
# data
dataset_name: 'satellite'
data_root: /mnt/A/satelite/datasets/
save_dir: checkpoints/predrnn_pp
gen_frm_dir: results/predrnn_pp
tb_log_dir: tb_log/predrnn_pp/
save_root: predrnn_pp_test/
input_length: 4
total_length: 12
img_width: 400
img_height: 300
img_channel: 1
num_workers: 4


# model
model_name: predrnn_pp
pretrained_model: /home/ices/yl/SatelliteSP/checkpoints/predrnn_pp/model-4400-0.0016259877416305243.ckpt
strict: true
num_hidden: 64,64,64,64
filter_size: 5
stride: 1
patch_size: 4
layer_norm: 1

# scheduled sampling
scheduled_sampling: 0
sampling_stop_iter: 10000
sampling_start_value: 1.0
sampling_changing_rate: 0.0001

# optimization
lr: 0.0001
max_iterations: 30000
lr_steps: [5000, 10000, 15000, 20000, 25000]
reverse_input: 1
batch_size: 4
epochs: 100
display_interval: 50
test_interval: 400
snapshot_interval: 5000
num_save_samples: 10
gpu_ids: [0]
