################################# training settings  #################################
# data
dataset_name: 'satellite'
data_root: /mnt/A/satelite/datasets/
save_dir: checkpoints/s2s_Invconvgru
gen_frm_dir: results/s2s_Invconvgru
tb_log_dir: tb_log/s2s_Invconvgru/
input_length: 4
total_length: 12
img_width: 400
img_height: 300
padding_H: 4 
padding_W: 0
img_channel: 1
num_workers: 4



# model
model_name: s2s_Invconvgru
pretrained_model: ~
strict: False
num_hidden: 64,32,16
filter_size: 5
stride: 1
patch_size: 2
layer_norm: 1
InvConv_h_num: 3

# scheduled sampling
scheduled_sampling: 0
sampling_stop_iter: 10000
sampling_start_value: 1.0
sampling_changing_rate: 0.0001

# optimization
lr: 0.0001
max_iterations: 80000
lr_steps: [5000, 10000, 15000, 20000, 25000]
reverse_input: 1
batch_size: 4
epochs: 100
display_interval: 50
test_interval: 1000
snapshot_interval: 5000
num_save_samples: 10
gpu_ids: [0]