################################# training settings  #################################
# data
dataset_name: 'radar'
# train_data_root: /mnt/data/radar/2hour/2019
# test_data_root: /mnt/data/radar/2hour/2020
train_data_root: /extend/radar_crop_data_360/train/train
test_data_root: /extend/radar_crop_data_360/valid
real_test_data_root: /extend/radar_crop_data_360/valid
# result
exp_name: GN-HTI-ConvGRU
result_root: /extend/qpf_radr/result/din_gru_lr_000005

input_length: 5
total_length: 25
img_width: 360
img_height: 360
test_width: 700
test_height: 900
padding_H: 0
padding_W: 0
test_pad_H: 0
test_pad_W: 8
img_channel: 1
num_workers: 4
testing_real : 0
# model
model_name: s2s_din_stgru
# 接着预训练的模型继续训练
pretrained_model: 
start_itr: 0
strict: True
num_hidden: [64,32,16] # for layer 3
# num_hidden: [64,32] # for layer 2
# num_hidden: [64,32,16,8] # for layer 4

filter_size: 5
stride: 1
patch_size: 1
layer_norm: True

# *************
activation: relu

# scheduled sampling
scheduled_sampling: 1
sampling_stop_iter: 20000
sampling_start_value: 1.0
sampling_changing_rate: 0.00005


# optimization
lr: 0.000005
max_iterations: 50000
lr_steps: [10000, 20000, 40000]
# lr_steps: ~
reverse_input: 0
batch_size: 4
test_batch_size: 8
epochs: 100
display_interval: 50
test_interval: 1000
snapshot_interval: 5000
num_save_samples: 10
is_test: 0
# **************
gpu_ids: [1]


# 模型的输入
# seq2seq模型decoder部分的输入
# dense情况下 gru的in需要等于out
# for the default setting layer_num  = 3
decode_in_channel: 128
decode_in_shape: [30, 30]
model:
  layer_num: 3
  encoder:
    downsample:
      - {k: 7, in: 1, out: 32, stride: 3}
      - {k: 5, in: 32, out: 64, stride: 2}
      - {k: 3, in: 64, out: 128, stride: 2}
    gru:
      # i2h和h2h分别是input2hidden的卷积核大小和hidden2hidden的卷积核大小
      - {in: 32, out: 32, i2h: 5, h2h: 5}
      - {in: 64, out: 64, i2h: 3, h2h: 3}
      - {in: 128, out: 128, i2h: 3, h2h: 3}
  decoder:
    num: 4
    upsample:
      - {k: 7, in: 32, out: 8, stride: 3}
      - {k: 5, in: 64, out: 32, stride: 2}
      - {k: 3, in: 128, out: 64, stride: 2}
    gru:
      - {in: 32, out: 32, i2h: 5, h2h: 5}
      - {in: 64, out: 64, i2h: 3, h2h: 3}
      - {in: 128, out: 128, i2h: 3, h2h: 3}
      # 最后一层GRU，并没有输入，所以i2h可以不要
    final:
      {k: 3, in: 8, out: 1, stride: 1}

# Addition layer number experiment: for the layer_num  = 2
# decode_in_channel: 64
# decode_in_shape: [60, 60]
# model:
#   layer_num: 2
#   encoder:
#     downsample:
#       - {k: 7, in: 1, out: 32, stride: 3}
#       - {k: 5, in: 32, out: 64, stride: 2}
#       # - {k: 3, in: 64, out: 128, stride: 2}
#     gru:
#       # i2h和h2h分别是input2hidden的卷积核大小和hidden2hidden的卷积核大小
#       - {in: 32, out: 32, i2h: 5, h2h: 5}
#       - {in: 64, out: 64, i2h: 3, h2h: 3}
#       # - {in: 128, out: 128, i2h: 3, h2h: 3}
#   decoder:
#     num: 4
#     upsample:
#       - {k: 7, in: 32, out: 8, stride: 3}
#       - {k: 5, in: 64, out: 32, stride: 2}
#       # - {k: 3, in: 128, out: 64, stride: 2}
#     gru:
#       - {in: 32, out: 32, i2h: 5, h2h: 5}
#       - {in: 64, out: 64, i2h: 3, h2h: 3}
#       # - {in: 128, out: 128, i2h: 3, h2h: 3}
#       # 最后一层GRU，并没有输入，所以i2h可以不要
#     final:
#       {k: 3, in: 8, out: 1, stride: 1}

# Addition layer number experiment: for the layer_num  = 4
# decode_in_channel: 256
# decode_in_shape: [15, 15]
# model:
#   layer_num: 4
#   encoder:
#     downsample:
#       - {k: 7, in: 1, out: 32, stride: 3}
#       - {k: 5, in: 32, out: 64, stride: 2}
#       - {k: 3, in: 64, out: 128, stride: 2}
#       - {k: 3, in: 128, out: 256, stride: 2}
#     gru:
#       # i2h和h2h分别是input2hidden的卷积核大小和hidden2hidden的卷积核大小
#       - {in: 32, out: 32, i2h: 5, h2h: 5}
#       - {in: 64, out: 64, i2h: 3, h2h: 3}
#       - {in: 128, out: 128, i2h: 3, h2h: 3}
#       - {in: 256, out: 256, i2h: 3, h2h: 3}
#   decoder:
#     num: 4
#     upsample:
#       - {k: 7, in: 32, out: 8, stride: 3}
#       - {k: 5, in: 64, out: 32, stride: 2}
#       - {k: 3, in: 128, out: 64, stride: 2}
#       - {k: 3, in: 256, out: 128, stride: 2}

#     gru:
#       - {in: 32, out: 32, i2h: 5, h2h: 5}
#       - {in: 64, out: 64, i2h: 3, h2h: 3}
#       - {in: 128, out: 128, i2h: 3, h2h: 3}
#       - {in: 256, out: 256, i2h: 3, h2h: 3}

#       # 最后一层GRU，并没有输入，所以i2h可以不要
#     final:
#       {k: 3, in: 8, out: 1, stride: 1}