################################# training settings  #################################
# data
dataset_name: 'radar'
# train_data_root: /mnt/data/radar/2hour/2019
# test_data_root: /mnt/data/radar/2hour/2020
train_data_root: /extend/radar_crop_data_360/train/train
test_data_root: /extend/radar_crop_data_360/valid
real_test_data_root: /extend/qpf_radar_test_align_nonrepated
gen_qpf_train_root: /extend/radar_for_qpf/train
# result
exp_name: PredRNN
result_root:  /extend/qpf_radr/result/pred_rnn_mse_4_layer/


input_length: 5
total_length: 25
img_width: 360
img_height: 360
test_width: 700
test_height: 900
padding_H: 0
padding_W: 0
test_pad_H: 0
test_pad_W: 8
img_channel: 1
num_workers: 4
tv_number: 4

# model
model_name: predrnn
pretrained_model: /extend/qpf_radr/result/pred_rnn_mse_4_layer/checkpoints/PredRNN/model-33000-0.47814256,0.2870894,0.056250673,0.0019742488.ckpt
start_itr: 0
strict: True
num_hidden: [64,64,64, 64]
filter_size: 5
stride: 1
patch_size: 4
# layer_norm: 1
layer_norm: True

# scheduled sampling
scheduled_sampling: 1
sampling_stop_iter: 20000
sampling_start_value: 1.0
sampling_changing_rate: 0.00005

# optimization
lr: 0.0001
max_iterations: 50000
lr_steps: [10000, 20000, 40000]
# lr_steps: ~
reverse_input: 0
batch_size: 4
test_batch_size: 4
epochs: 100
display_interval: 50
test_interval: 1000
snapshot_interval: 4000
num_save_samples: 10
# **************
gpu_ids: [0]


# 模型的输入
# seq2seq模型decoder部分的输入
decode_in_channel: 16
decode_in_shape: [90, 90]
model:
  layer_num: 3
  encoder:
    downsample:
      - {k: 7, in: 1, out: 64, stride: 4}
      - {k: 5, in: 32, out: 64, stride: 2}
      - {k: 3, in: 64, out: 128, stride: 2}
    lstm:
      # i2h和h2h分别是input2hidden的卷积核大小和hidden2hidden的卷积核大小
      - {in: 32, out: 32, i2h: 5, h2h: 5}
      - {in: 64, out: 64, i2h: 3, h2h: 3}
      - {in: 128, out: 128, i2h: 3, h2h: 3}
  decoder:
    num: 1
    upsample:
      - {k: 7, in: 64, out: 8, stride: 4}
      - {k: 5, in: 64, out: 32, stride: 2}
      - {k: 3, in: 128, out: 64, stride: 2}
    lstm:
      - {in: 32, out: 32, i2h: 5, h2h: 5}
      - {in: 64, out: 64, i2h: 3, h2h: 3}
      - {in: 128, out: 128, i2h: 3, h2h: 3}
      # 最后一层lstm，并没有输入，所以i2h可以不要
    final:
      {k: 3, in: 8, out: 1, stride: 1}